apiVersion: apps/v1
kind: Deployment
metadata:
  name: week10hw-app
  labels:
    app: week10hw-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: week10hw-app
  template:
    metadata:
      labels:
        app: week10hw-app
    spec:
      containers:
        - name: week10hw-app
          image: arazz/ohjelmistotuotantoprojekti-1-tx00ey27-3009:origin-Week_10HW
          imagePullPolicy: Never   # use Never for local images
          env:
            - name: DISPLAY
              value: "host.minikube.internal:0.0"
            - name: JAVA_TOOL_OPTIONS
              value: "-Dprism.order=sw"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"