apiVersion: apps/v1
kind: Deployment
metadata:
  name: week13hw-app
  labels:
    app: week13hw-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: week13hw-app
  template:
    metadata:
      labels:
        app: week13hw-app
    spec:
      containers:
        - name: week13hw-app
          image: arazz/ohjelmistotuotantoprojekti-1-tx00ey27-3009:origin-Week_13HW
          imagePullPolicy: Never   # use Never for local images
          env:
            - name: DISPLAY
              value: "host.minikube.internal:0.0"
            - name: JAVA_TOOL_OPTIONS
              value: "-Dprism.order=sw"

            - name: DISPLAY
              value: "host.minikube.internal:0.0"
            - name: JAVA_TOOL_OPTIONS
              value: "-Dprism.order=sw"

            - name: DB_URL
              value: "jdbc:mysql://localhost:3306/sep2_week3hw"

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD

          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"